services:
  gc_registry:
    restart: "${RESTART-no}"
    environment:
      - TC_HOST=host.docker.internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./gc_registry:/code/gc_registry"
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: poetry run uvicorn --reload "gc_registry.main:app" --host 0.0.0.0 --port 4200 --log-level debug
    env_file:
      - .env
    depends_on:
      - db_write
      - db_read
    ports:
      - "4200:4200"

  db_write:
    image: postgres:13
    volumes:
      - postgres_data_write:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5436:5432"

  db_read:
    image: postgres:13
    volumes:
      - postgres_data_read:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=read
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5438:5432"

volumes:
  gc_registry:
  postgres_data_write:
  postgres_data_read: