schema_paths_read = [
    "src.schemas.authentication.TokenBlacklist",
    "src.schemas.authentication.SecureAPIUser",
    "src.schemas.account.Account",
    "src.schemas.device.Device",
    "src.schemas.organisation.Organisation",
    "src.schemas.user_account_link.UserAccountLink",
    "src.schemas.user.User",
    "src.schemas.measurement.MeasurementReport",
    "src.schemas.certificate.GranularCertificateBundle",
    "src.schemas.certificate_action.GranularCertificateAction",
    "src.schemas.storage.StorageChargeRecord",
    "src.schemas.storage.StorageDischargeRecord",
    "src.schemas.storage_action.StorageAction",
]

schema_paths_write = [
    "src.schemas.authentication.TokenBlacklist",
    "src.schemas.authentication.SecureAPIUser",
    "src.schemas.account.Account",
    "src.schemas.device.Device",
    "src.schemas.organisation.Organisation",
    "src.schemas.user_account_link.UserAccountLink",
    "src.schemas.user.User",
    "src.schemas.measurement.MeasurementReport",
    "src.schemas.certificate.GranularCertificateBundle",
    "src.schemas.certificate_action.GranularCertificateAction",
    "src.schemas.storage.StorageChargeRecord",
    "src.schemas.storage.StorageDischargeRecord",
    "src.schemas.storage_action.StorageAction",
]
