schema_paths_read = [
    "gc_registry.authentication.models.TokenBlacklist",
    "gc_registry.authentication.models.SecureAPIUser",
    "gc_registry.account.models.Account",
    "gc_registry.device.models.Device",
    "gc_registry.organisation.models.Organisation",
    "gc_registry.user.models.UserAccountLink",
    "gc_registry.user.models.User",
    "gc_registry.measurement.models.MeasurementReport",
    "gc_registry.certificate.models.GranularCertificateBundle",
    "gc_registry.certificate.models.GranularCertificateAction",
    "gc_registry.storage.models.StorageChargeRecord",
    "gc_registry.storage.models.StorageDischargeRecord",
    "gc_registry.storage.models.StorageAction",
]

schema_paths_write = [
    "gc_registry.authentication.models.TokenBlacklist",
    "gc_registry.authentication.models.SecureAPIUser",
    "gc_registry.account.models.Account",
    "gc_registry.device.models.Device",
    "gc_registry.organisation.models.Organisation",
    "gc_registry.user.models.UserAccountLink",
    "gc_registry.user.models.User",
    "gc_registry.measurement.models.MeasurementReport",
    "gc_registry.certificate.models.GranularCertificateBundle",
    "gc_registry.certificate.models.GranularCertificateAction",
    "gc_registry.storage.models.StorageChargeRecord",
    "gc_registry.storage.models.StorageDischargeRecord",
    "gc_registry.storage.models.StorageAction",
    "gc_registry.core.database.cqrs.Event",
]
