schema_paths_read = [
    "src.schemas.authentication.TokenBlacklist",
    "src.schemas.authentication.SecureAPIUser",
    "src.schemas.entities.Account",
    "src.schemas.entities.Device",
    "src.schemas.entities.Organisation",
    "src.schemas.entities.UserAccountLink",
    "src.schemas.entities.User",
    "src.schemas.entities.MeasurementReport",
    "src.schemas.certificate.GranularCertificateBundle",
    "src.schemas.certificate.GranularCertificateAction",
    "src.schemas.storage.StorageChargeRecord",
    "src.schemas.storage.StorageDischargeRecord",
    "src.schemas.storage.StorageAction",
]

schema_paths_write = [
    "src.schemas.authentication.TokenBlacklist",
    "src.schemas.authentication.SecureAPIUser",
    "src.schemas.entities.Account",
    "src.schemas.entities.Device",
    "src.schemas.entities.Organisation",
    "src.schemas.entities.UserAccountLink",
    "src.schemas.entities.User",
    "src.schemas.entities.MeasurementReport",
    "src.schemas.certificate.GranularCertificateBundle",
    "src.schemas.certificate.GranularCertificateAction",
    "src.schemas.storage.StorageChargeRecord",
    "src.schemas.storage.StorageDischargeRecord",
    "src.schemas.storage.StorageAction",
]
