"""merge_changes

Revision ID: 311efcb82e7b
Revises: 172d3692339f
Create Date: 2024-10-10 10:01:39.791491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '311efcb82e7b'
down_revision: Union[str, None] = '172d3692339f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_ids', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('account', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('account', 'ids')
    op.add_column('device', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('granularcertificateaction', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('granularcertificateaction', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('granularcertificateaction', 'certificate_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum(name='certificate_status'),
               postgresql_using="certificate_status::certificate_status",
               existing_nullable=True)
    op.drop_column('granularcertificateaction', 'action_id')
    op.alter_column('granularcertificatebundle', 'certificate_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum(name='certificate_status'),
               postgresql_using="certificate_status::certificate_status",
               existing_nullable=True)
    op.add_column('measurementreport', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('organisation', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('secureapiuser', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('storageaction', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('storagechargerecord', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('storagedischargerecord', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tokenblacklist', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('roles', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('user', 'role')
    op.add_column('useraccountlink', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useraccountlink', 'is_deleted')
    op.add_column('user', sa.Column('role', postgresql.ARRAY(sa.VARCHAR()),  nullable=True))
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'roles')
    op.drop_column('tokenblacklist', 'is_deleted')
    op.drop_column('storagedischargerecord', 'is_deleted')
    op.drop_column('storagechargerecord', 'is_deleted')
    op.drop_column('storageaction', 'is_deleted')
    op.drop_column('secureapiuser', 'is_deleted')
    op.drop_column('organisation', 'is_deleted')
    op.drop_column('measurementreport', 'is_deleted')
    op.alter_column('granularcertificatebundle', 'certificate_status',
               existing_type=sa.Enum(name='certificate_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('granularcertificateaction', sa.Column('action_id', sa.INTEGER(), nullable=False))
    op.alter_column('granularcertificateaction', 'certificate_status',
               existing_type=sa.Enum(name='certificate_status'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('granularcertificateaction', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('granularcertificateaction', 'is_deleted')
    op.drop_column('device', 'is_deleted')
    op.add_column('account', sa.Column('ids', postgresql.ARRAY(sa.VARCHAR()),  nullable=True))
    op.drop_column('account', 'is_deleted')
    op.drop_column('account', 'user_ids')
    # ### end Alembic commands ###