"""update_gc_action_class

Revision ID: 5be2b34d1ce9
Revises: 531858c09090
Create Date: 2024-10-30 12:21:25.798715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5be2b34d1ce9'
down_revision: Union[str, None] = '531858c09090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('granularcertificateaction', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('granularcertificateaction', sa.Column('action_response_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('granularcertificateaction', 'id_to_update_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('granularcertificateaction', sa.Column('id_to_update_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('granularcertificateaction', 'action_response_status')
    op.drop_column('granularcertificateaction', 'device_id')
    # ### end Alembic commands ###