"""change_meter_data_id

Revision ID: 700a826fe562
Revises: 9eeb502c46a9
Create Date: 2024-12-19 18:00:29.371327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '700a826fe562'
down_revision: Union[str, None] = '9eeb502c46a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('local_device_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('device', 'meter_data_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('meter_data_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('device', 'local_device_identifier')
    # ### end Alembic commands ###