"""standardise_naming

Revision ID: 9eeb502c46a9
Revises: cd5332cc273e
Create Date: 2024-11-29 16:35:31.825298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eeb502c46a9'
down_revision: Union[str, None] = 'cd5332cc273e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('granularcertificateaction', sa.Column('certificate_quantity', sa.Integer(), nullable=True))
    op.add_column('granularcertificateaction', sa.Column('certificate_bundle_percentage', sa.Float(), nullable=True))
    op.add_column('granularcertificateaction', sa.Column('certificate_bundle_status', sa.Enum('ACTIVE', 'CANCELLED', 'CLAIMED', 'EXPIRED', 'WITHDRAWN', 'LOCKED', 'RESERVED', 'BUNDLE_SPLIT', name='certificatestatus'), nullable=True))
    op.add_column('granularcertificatebundle', sa.Column('certificate_bundle_status', sa.Enum('ACTIVE', 'CANCELLED', 'CLAIMED', 'EXPIRED', 'WITHDRAWN', 'LOCKED', 'RESERVED', 'BUNDLE_SPLIT', name='certificatestatus'), nullable=False))
    op.add_column('granularcertificatebundle', sa.Column('certificate_bundle_id_range_start', sa.BigInteger(), nullable=True))
    op.add_column('granularcertificatebundle', sa.Column('certificate_bundle_id_range_end', sa.BigInteger(), nullable=True))
    op.drop_column('granularcertificatebundle', 'bundle_id_range_start')
    op.drop_column('granularcertificatebundle', 'bundle_id_range_end')
    op.drop_column('granularcertificatebundle', 'certificate_status')
    op.add_column('storagechargerecord', sa.Column('granular_certificate_certificate_bundle_id_range_start', sa.Integer(), nullable=False))
    op.add_column('storagechargerecord', sa.Column('granular_certificate_certificate_bundle_id_range_end', sa.Integer(), nullable=False))
    op.drop_column('storagechargerecord', 'gc_bundle_id_range_start')
    op.drop_column('storagechargerecord', 'gc_bundle_id_range_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storagechargerecord', sa.Column('gc_bundle_id_range_end', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('storagechargerecord', sa.Column('gc_bundle_id_range_start', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('storagechargerecord', 'granular_certificate_certificate_bundle_id_range_end')
    op.drop_column('storagechargerecord', 'granular_certificate_certificate_bundle_id_range_start')
    op.add_column('granularcertificatebundle', sa.Column('certificate_status', postgresql.ENUM('ACTIVE', 'CANCELLED', 'CLAIMED', 'EXPIRED', 'WITHDRAWN', 'LOCKED', 'RESERVED', 'BUNDLE_SPLIT', name='certificatestatus'), autoincrement=False, nullable=False))
    op.add_column('granularcertificatebundle', sa.Column('bundle_id_range_end', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('granularcertificatebundle', sa.Column('bundle_id_range_start', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('granularcertificatebundle', 'certificate_bundle_id_range_end')
    op.drop_column('granularcertificatebundle', 'certificate_bundle_id_range_start')
    op.drop_column('granularcertificatebundle', 'certificate_bundle_status')
    op.drop_column('granularcertificateaction', 'certificate_bundle_status')
    op.drop_column('granularcertificateaction', 'certificate_bundle_percentage')
    op.drop_column('granularcertificateaction', 'certificate_quantity')
    # ### end Alembic commands ###